### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [lucafont2/pearson-downloader#1]
Hi, 
I'm getting following error while running the script:

/home/max/Downloads/pearson-downloader-master/core/eText.js:13
    u;p;
     ^

SyntaxError: Unexpected token ;
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>

could you advise how to solve?
Thanks

**Comment by ghost** [comment]
What version of node do you have

**Comment by ghost** [comment]
Previously I had 8, now I moved to 17.1.0 and I got the following error:

max@ubuntu:~/Downloads/pearson-downloader-master$ node -v
v17.1.0
max@ubuntu:~/Downloads/pearson-downloader-master$ node main.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- /home/max/Downloads/pearson-downloader-master/core/eText.js
- /home/max/Downloads/pearson-downloader-master/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/max/Downloads/pearson-downloader-master/core/eText.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/max/Downloads/pearson-downloader-master/core/eText.js',
    '/home/max/Downloads/pearson-downloader-master/main.js'
  ]
}

Node.js v17.1.0

**Comment by ghost** [comment]
You have to run `npm install` inside the folder of the project as written on the readme

**Comment by ghost** [comment]
Closing this, if you still have issues please comment below, please read the readme as i just updated it

**Comment by ghost** [comment]
Thanks for your help. Unfortunately I'm still having issues with a brand new error. See below:

max@ubuntu:~/Downloads/pearson-downloader-master$ npm install

up to date, audited 11 packages in 1s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
max@ubuntu:~/Downloads/pearson-downloader-master$ node main.js
**SCRAPING WITH:** eyJraWQiOiJrMjU0OC4xNjAyOTEzNzczIiwiYWxnIjoiUlM1MTIifQ.eyJzdWIiOiI2YWY2YjgxODk4OTI0ZjIxODM4NmFhNWE5ZGQyOWVhYiIsImhjYyI6IklUIiwidHlwZSI6ImF0IiwiZXhwIjoxNjM3NDkwNzI4LCJkZXZpY2VpZCI6ImM5ZWZjNDgxYmFmMTJmY2ZmMzQ0NzQwNCIsImlhdCI6MTYzNzQ4ODkyOCwiY2xpZW50X2lkIjoiMm9WR0IzSnVoajJFVVJoSVJFbjVHUFlnaWpCbTc2MzQiLCJzZXNzaWQiOiI4YjJkYTk2Ny1kZmJhLTQwNjgtOTc0ZS1kYmIxZTdmZWVlOWQifQ.rWxouwJaM-ZlFC1RptdUQMLG3vIqMTzh9818OIPKbQAVbN5nCdeHglIciReXL3Vrr23vgDAG2Q03mV07PSoyPiNZeLukac6K5EUJz57rgdDmb500IDHjXzisCygY9yc8cYjddckHeKLM_GAa7_FnwSlc3XcMZqVXjDSi3DuUWK6NYIx4_EubrJeSUT5ewlH9N8U3klNl9UnPtKdU30hcsnMo5UDVYLGKdUuRPDHeA8Lg17kxrc5UTOk8UX0fszhh-1QOSBqlOCSMGD4FDQhKR8bgcRWvFPjNID86PtY5Jb2ZELRRJkfT2GMDsejDOxVHB5fxFDSNSvkbQPuN0R98Iw

**Comment by ghost** [comment]
Hello, this is the correct behaviour of the code. After the scrape with your credentials the code will output all books on your account. 
Here is an example. I have just ran the code and it is working perfectly. Maybe you dont have any books fot pearson e-text?

>node main.js
```
SCRAPING WITH: eyJraWQiOiJrMjU0OC4xNjAyOTEzNzczIiw...6fP63R86MIcydObG8ulLlTk9w0Z23ew
Proseguire con il download di Book1  (y/n) default: n > y
DOWNLOADING

DONE

true
Proseguire con il download di Books2  (y/n) default: n > y
DOWNLOADING

DONE

true

Exiting
```

**Comment by ghost** [comment]
Thanks.
I got just one book with the following URL: 

https://reader-prod.gls.pearson-intl.com/product/60e876edc70d56714303e196

does this mean it works in a different way?
Thanks

**Comment by ghost** [comment]
Hello, this url is not for the pearson e-text, unfortunately this program is currently only for e-text. If you would like me to take a look to this other pearson reader and if you dont mind giving me the credentials you can rach me on telegram @lucazio22  an i will try to add to the code if it is possible
